# Generated by Django 4.0.3 on 2022-04-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JsonReceivedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.CharField(max_length=100)),
                ("jsonId", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("completed", models.CharField(max_length=100)),
            ],
        ),
    ]
